test_suites:
    - name: lint
      script_path: /root/okta/siw-next/scripts
      sort_order: '1'
      timeout: '10'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit-jest
      script_path: /root/okta/siw-next/scripts
      sort_order: '2'
      timeout: '15'
      script_name: unit-jest
      criteria: MERGE
      queue_name: small
    - name: e2e
      script_path: /root/okta/siw-next/scripts
      sort_order: '3'
      timeout: '15'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: publish
      script_path: /root/okta/siw-next/scripts
      sort_order: '9'
      timeout: '60'
      script_name: publish
      criteria: MERGE
      queue_name: small
